# TypeProf 0.21.3

# Classes
module Submodule
  def submethod: -> nil
end

module Example
  class App
    HOGE: String
    FUGA: String
    extend Submodule
    include Submodule

  # def initialize: (Integer, String) -> void
  # def foo: () -> bool
  # def self.classmethod: () -> void
  # attr_reader x: Integer
  # attr_accessor y: String
  # attr_writer z: Array[untyped]

    private
    def bar: (untyped zz) -> untyped
  end
end
