# TypeProf 0.21.3

# Classes
module Submodule
  def submethod: -> nil
end

module Example
  class App
    HOGE: String
    FUGA: Integer
    extend Submodule
    include Submodule

  # def initialize: (Integer, String) -> void
  # def foo: () -> bool
  # def self.classmethod: () -> void
  # def bar: [T] (T) -> T
  # attr_reader xxx: Integer
  # attr_accessor yyy: String
  # attr_writer zzz: Array[untyped]
  end
end
